# Generated by Django 3.1.7 on 2021-04-02 16:31

import classifiers.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Model ID')),
                ('model_name', models.CharField(help_text='A user-friendly name for the model', max_length=30, verbose_name='Model Name')),
                ('model_desc', models.CharField(help_text='A user-friendly name for the model', max_length=50, verbose_name='Model Description')),
                ('model_file', models.FileField(help_text='The HDF5 containing the model', upload_to=classifiers.models.MLModel.get_model_filename)),
            ],
        ),
    ]
