# Generated by Django 3.1.7 on 2021-04-10 10:12

import classifiers.models
import classifiers.storages
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Model ID')),
                ('model_name', models.CharField(help_text='A user-friendly name for the model', max_length=30, unique=True, verbose_name='Model Name')),
                ('model_desc', models.CharField(help_text='A short description of the model that can help the user make a decision', max_length=50, verbose_name='Model Description')),
                ('model_file', models.FileField(help_text='The HDF5 containing the model', storage=classifiers.storages.MLModelStorage(), upload_to=classifiers.models.MLModel.get_model_filename)),
                ('loss_curve', models.ImageField(help_text='The loss curve of the model', upload_to=classifiers.models.MLModel.get_loss_curve_filename)),
                ('accuracy', models.FloatField(default=0.0, editable=False, help_text='The accuracy of the model')),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
            },
        ),
    ]
