# Generated by Django 3.1.7 on 2021-04-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='clr',
            field=models.TextField(default='', editable=False, help_text='The classification report of the model (generated when saved)', max_length=500, verbose_name='Classification Report'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='accuracy',
            field=models.FloatField(default=0.0, editable=False, help_text='The accuracy of the model (calculated when saved)'),
        ),
    ]
