# Generated by Django 3.1.7 on 2021-04-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmodel',
            options={'verbose_name': 'ML Model', 'verbose_name_plural': 'ML Models'},
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_name',
            field=models.CharField(help_text='A user-friendly name for the model', max_length=30, unique=True, verbose_name='Model Name'),
        ),
    ]
