# Generated by Django 3.2 on 2021-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0002_auto_20210410_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='conv_layers',
            field=models.JSONField(default={}, editable=False, help_text='The # and size of filters of each convolutional layer (detected when saved)', verbose_name='Convolutional Layers'),
        ),
    ]
