# Generated by Django 3.1.7 on 2021-04-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0002_auto_20210402_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_desc',
            field=models.CharField(help_text='A short description of the model that can help the user make a decision', max_length=50, verbose_name='Model Description'),
        ),
    ]
