# Generated by Django 3.1.7 on 2021-04-02 18:06

import classifiers.models
import classifiers.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0003_auto_20210402_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_file',
            field=models.FileField(help_text='The HDF5 containing the model', storage=classifiers.storages.MLModelStorage(), upload_to=classifiers.models.MLModel.get_model_filename),
        ),
    ]
