# Generated by Django 3.2 on 2021-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0003_mlmodel_conv_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='conv_layers',
            field=models.JSONField(default=str, editable=False, help_text='The # and size of filters of each convolutional layer (detected when saved)', verbose_name='Convolutional Layers'),
        ),
    ]
