# Generated by Django 3.2 on 2021-04-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0004_alter_mlmodel_conv_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='clr',
            field=models.JSONField(default=str, editable=False, help_text='The classification report of the model (generated when saved)', verbose_name='Classification Report'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_desc',
            field=models.CharField(help_text='A short description of the model that can help the user make a decision', max_length=200, verbose_name='Model Description'),
        ),
    ]
